server {
  listen 80;
  server_name _;
  root /usr/share/nginx/html;
  index index.html;
  include /etc/nginx/mime.types;
  default_type application/octet-stream;
  location / {
    add_header Cache-Control "no-store, no-cache, must-revalidate" always;
    add_header Pragma "no-cache" always;
    try_files $uri $uri/ =404;
  }
}
